server:
  host: 127.0.0.1
  port: 22
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: test
array:
  names:
    - zhang: [ "ray", "run" ]
    - li: ["ray", "run"]
  ages:
    - 1
    - 2
    - 3
    - 4
